DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS report;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    preferred_beach TEXT
);

CREATE TABLE report (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    shark_type TEXT NOT NULL,
    beach TEXT NOT NULL,
    size TEXT,
    FOREIGN KEY (author_id) REFERENCES user(id) ON DELETE CASCADE
);
